### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by ryanhammonds** [voytekresearch/timescale-methods#18]
- [x] move the manuscript figures notebook into separate notebooks
- [x] deprecate all of the old/unused notebooks
- [x] create a gh pages site
  - [x] API
  - [x] figures 
  - [x] add simulation example 
  - [x] add example of how to use the PSD and ACF classes
  - [x] add example of AR-PSD vs non-parametric PSD
  - [ ] add example for the decomposition sub-module
